In [41]:
import numpy as np

In [3]:
x = [1,20,3,400,5]
y = np.array(x)

print (y.max())
print (y.min())
print (np.argmax(y))
print (np.argmin(y))

400
1
3
0


Fungsi argmax & argmin untuk melihat nilai max & min ada di indeks ke berapa dari matriks.

In [4]:
x = [[1,20,3,400,5], [3,5,7,9,11]]
y = np.array(x)

print (y.max())
print (y.min())
print (np.argmax(y))
print (np.argmin(y))

400
1
3
0


Bisa cek langsung dalam sebuah matriks besar meski beda elemen

__Tips Reshape__ </br>
-1 untuk memaksakan dimensi

In [5]:
print (y.shape)
print (y.reshape(-1))
print (y.reshape(5,-1))

(2, 5)
[  1  20   3 400   5   3   5   7   9  11]
[[  1  20]
 [  3 400]
 [  5   3]
 [  5   7]
 [  9  11]]


Dari dimensi (2,5) dipaksakan menjadi (10) dan (5,2) menggunakan -1
</br>
----

__Matriks Identitas__

In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,0,0],[0,0,0]])
c = np.zeros((2,3))
print (a + b)
print (a + c)
print (b)
print (c)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print (b.dtype)
print (c.dtype)

int64
float64


In [8]:
b = np.array([[0,0,0],[0,0,0]])
c = np.zeros((2,3), dtype="int64")
print (b)
print (b.dtype)
print (c)
print (c.dtype)

[[0 0 0]
 [0 0 0]]
int64
[[0 0 0]
 [0 0 0]]
int64


In [9]:
d = np.ones((3,3))
print (d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
x = np.zeros((3,3),dtype=bool)
print (x)

x = np.ones((3,3), dtype=bool)
print (x)

lain = np.full((3,3), 0, dtype=bool)
print (lain)

lain = np.full((3,3), 1, dtype=bool)
print (lain)

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Prinsip 0 = False, dan 1 = True </br>

In [11]:
print (lain)
print (type(lain))
print (lain.tolist())
print (type(lain.tolist()))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
[[True, True, True], [True, True, True], [True, True, True]]
<class 'list'>


Mengubah numpy array menjadi bentuk list dengan menggunakan .tolist()
</br>
----

In [12]:
x = [0,1,2,3,4]
y = [5,6,7,8,9]

Mengubah menjadi z = [[0,1,2,3,4],[5,6,7,8,9]]

__Cara 1__ </br>
Menggunakan append

In [13]:
z = []
z.append(x)
z.append(y)
print (z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 2__
</br>Menggunakan identitas

In [14]:
z = [x,y]
print (z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 3__
</br>Menggunakan nparray

In [15]:
z = np.array(x+y).reshape(2,-1).tolist()
print(z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 4__
</br>Menggunakan extend

In [16]:
a = []
a.extend(x)
a.extend(y)
z = np.array(a).reshape(2,-1).tolist()
print(z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 5__
</br>Menggunakan concatenate

In [17]:
xnp = np.array(x)
ynp = np.array(y)
z = np.concatenate([[xnp],[ynp]], axis=0).tolist()
print(z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 6__
</br>Menggunakan vstack

In [18]:
z = np.vstack([xnp, ynp]).tolist()
print (z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 7__
</br>Menggunakan r

In [20]:
z = np.r_[[xnp], [ynp]].tolist()
print (z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


__Cara 8__
</br>Menggunakan rowstack

In [21]:
z = np.row_stack((xnp,ynp)).tolist()
print (z)

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


#### Vstack & Hstack

In [22]:
a = np.arange(6).reshape(2,-1)
b = np.array([5,6,7,8,9,10]).reshape(2,-1)

c = np.vstack([a,b])
print (c)

c = np.hstack([a,b])
print (c)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2  5  6  7]
 [ 3  4  5  8  9 10]]


__Opsi lain Vstack__

In [23]:
d = np.concatenate([a,b],axis=0)
e = np.row_stack((a,b))
f = np.r_[a,b]
print (d)
print (e)
print (f)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


----

__Condition__

In [25]:
z = np.arange(1,11)
print (z)

[ 1  2  3  4  5  6  7  8  9 10]


Tampilkan hanya yang genap

In [26]:
print (z[1::2])
print(z[z%2 == 0])

[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [27]:
print(np.where(z % 2 != 0, 0, z))

[ 0  2  0  4  0  6  0  8  0 10]


z % 2 != 0 adalah kondisi </br>
0 adalah produk akhir </br>
z adalah sumber </br>
----

__Range__

In [30]:
x = np.arange(10,20)
print (np.where(x<16))
print (x[np.where(x<16)])
print (x[np.arange(3)])

(array([0, 1, 2, 3, 4, 5]),)
[10 11 12 13 14 15]
[10 11 12]


In [32]:
print (x[np.where((x>14) & (x<18))])
print (x[np.where(np.logical_and(x>14,x<18))])
print (x[(x>14) & (x<18)])

[15 16 17]
[15 16 17]
[15 16 17]


----

__Determinant__

In [33]:
x = np.array([[3,1],[2,5]])
print (x)
print (np.linalg.det(x))

[[3 1]
 [2 5]]
13.0


Fungsi untuk mencari determinan adalah np.linalg.det()

In [34]:
y = np.array([
    [1,2,1],
    [3,3,1],
    [2,1,2]
])
print (y)
print (np.linalg.det(y))

[[1 2 1]
 [3 3 1]
 [2 1 2]]
-6.0


In [38]:
z = np.array([
    [3,2], [1,4]
])
print (z)
print (np.linalg.inv(z))
print (z@np.linalg.inv(z))

[[3 2]
 [1 4]]
[[ 0.4 -0.2]
 [-0.1  0.3]]
[[1. 0.]
 [0. 1.]]


----
__Dot and Cross__

In [39]:
print (z@np.linalg.inv(z))
print (z.dot(np.linalg.inv(z)))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
print (z.)

In [44]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 4), np.tile(a, 4)]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3])