In [2]:
import numpy as np

In [2]:
x = [1,2,3,4,5]
y = np.array(x)

print (x)
print (y)
print (x + x)
print (y + y)

numpy array menghitung dalam bentuk matriks
numpy array bisa membuat file dalam bentuk list atau tuple

In [5]:
x = [
    [1,2,3], [4,5,6]
]
y = np.array(x)

untuk melihat indeks ke-n, bisa menggunakan (,)

In [6]:
print (x[1][1])
print (y[1,1])

5
5


----

### Cek dimensi Matriks

Menggunakan syntax ndim

In [7]:
x = [1,2,3]
x = np.array(x)
y = [[1,2,3], [4,5,6]]
y = np.array(y)
z = [[[1,2,3], [4,5,6], [7,8,9]]]
z = np.array(z)

print (x)
print (x.ndim)
print (y)
print (y.ndim)
print (z)
print (z.ndim)

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


__Another Syntax__
</br>size = melihat besar konten
</br>dtype = melihat jenis konten

In [8]:
z = [[[1,2,3], [4,5,6], [7,8,9]]]
z = np.array(z)

print (z.size)
print (z.dtype)
print (z.itemsize)

9
int64
8


In [9]:
z = z.astype("float64")

print (z)
print (z.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


__Melihat shape dari sebuah matriks__

In [11]:
z = [[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]
z = np.array(z)
print (z.ndim)
print (z.shape)

3
(1, 3, 4)


Dimensi 3 > List level 3
</br> Shape (1,3,4) = Dimensi 1 ada 1 elemen, dimensi 2 ada 3 elemen, dimensi 3 ada 4 elemen

__Membuat range dari sebuah array__

In [12]:
print(np.arange(1,10,2))
print(list(range(1,10,2)))

[1 3 5 7 9]
[1, 3, 5, 7, 9]


yang atas berupa array, yang bawah berupa list. Prinsipnya pun sama (start, stop, step)

----

__Random__

In [13]:
print (np.random.random(10))

[0.15457699 0.8450429  0.79745426 0.71201876 0.39306921 0.35262873
 0.63361648 0.14669469 0.24083358 0.36308191]


Menghasilkan 10 angka random dalam 1 dimensi, dengan value dari 0-1

In [14]:
print (np.random.rand(2,4))

[[0.96942566 0.30812414 0.49518818 0.83289644]
 [0.8475932  0.26019647 0.05261942 0.76401059]]


Menghasilkan 2 dimensi dengan 4 konten angka random, dengan value dari 0-1

In [15]:
print (np.random.randint(7, size=10))
print (np.random.randint(7, size=(2,5)))

[1 6 0 5 4 1 0 3 0 4]
[[2 1 6 6 6]
 [4 4 2 1 3]]


Atas : Menghasilkan angka random dengan dimensi 1,10 dengan value maksimal 7 </br>
Bawah : Menghasilkan angka random dengan dimensi 2,5 dengan value maksimal 7

----

__Spacing__

In [18]:
print (np.linspace (1,5,5))
print (np.linspace (0,100,5))

[1. 2. 3. 4. 5.]
[  0.  25.  50.  75. 100.]


(batas bawah, batas atas, jumlah)

In [20]:
a = [(1,2,3), (4,5,6), (7,8,9)]
a = np.array(a)

print (a[0,2])
print (a[0:, 2])
print (a[0:, 0:2])
print (a[0:, 0])
print (a[0:, :1])

3
[3 6 9]
[[1 2]
 [4 5]
 [7 8]]
[1 4 7]
[[1]
 [4]
 [7]]


In [21]:
a = [(1,2,3,4,5), (4,5,6,7,8), (7,8,9,10,11)]
a = np.array(a)

print (a[0:, (0,-1)])
print (a[0:, :1])
print (a[0:, :1].shape)
print (a[0:, :1].size)
print (a[0:, 0])
print (a[0:, 0].shape)
print (a[0:, 0].size)

[[ 1  5]
 [ 4  8]
 [ 7 11]]
[[1]
 [4]
 [7]]
(3, 1)
3
[1 4 7]
(3,)
3


Matriks dengan size yang sama, bisa di-reshape

In [22]:
print (a[0:, :1].reshape(3,))
print (a[0:, 0])

[1 4 7]
[1 4 7]


----

#### Max and Min

In [7]:
x = [1,4,5,2,3]
y = np.array(x)

print (max(x))
print (min(x))

print (y.max())
print (y.min())

5
1
5
1


In [8]:
print (np.sort(y))

[1 2 3 4 5]


In [9]:
def makmin (x):
    y = np.array(x)
    y = np.sort(y)
    max = y[-1]
    min = y[0]
    return (f"Min = {min} & Max = {max}")

x = [3,1,5,6,8,4,9]
print (makmin(x))

Min = 1 & Max = 9


In [11]:
from functools import reduce
xsum = reduce(lambda a,b: a+b, x)
print (xsum)

36


In [12]:
xmax = reduce(lambda a,b : a if (a>b) else b, x)
xmin = reduce(lambda a,b : a if (a<b) else b, x)
print (xmax)
print (xmin)

9
1


----

#### Mean and Median 

In [13]:
y = np.array(x)
print (np.mean(y))
print (np.median(y))

5.142857142857143
5.0


----

#### Trigonometri

In [14]:
print (np.pi)
print (np.sin(0))
print (np.cos(0))

3.141592653589793
0.0
1.0
